"""route_to_lane — first-class P1→specialist-lane handoff tool (Phase A).

Why this exists (WTS f875d95c, punch-list aa752852):
  P1 used to hand-shell the lane wrapper with the WRONG syntax
  (`dd-visible-lane-run qa <packet>`), which the wrapper rejected with
  `unknown arg: qa` (exit 2) — yet P1 reported "now sending it through the
  wrapper" as if the handoff succeeded. The QA lane never ran.

This tool fixes the three Phase-A issues:
  I1  — emit the CORRECT invocation: `dd-visible-lane-run --lane <lane>
        --packet <path> [--wts-task <id>]`. P1 calls this tool; it never
        hand-builds wrapper args, so the positional-arg break is impossible.
  I2  — verify honestly: capture the wrapper exit_code AND the normalized
        status line it prints. Report SUCCESS only when exit==0 AND the lane
        actually ran and returned a result line. On non-zero exit / no result,
        return a FAILED result with the captured stderr — never a false success.
  I3  — attach to the ACTIVE bound task: pass `--wts-task <id>` through to the
        wrapper so the handoff artifact lands on the thread's active WTS task;
        the per-lane standing "lane log" bucket is only a loud last-resort
        (the wrapper logs a WARN when it falls back).

Read-only on comms.db is fine; this tool does not write Slack/DB directly — all
posting/attachment happens inside the sanctioned wrapper (dd-slack-service API).
"""
from __future__ import annotations

import json
import os
import subprocess
from pathlib import Path
from typing import Optional

import re

from tools.p1_caller_boundary import require_p1_caller
from tools.registry import registry, tool_error
try:
    from tools.engineering_pool_selector import select_engineering_lane
except Exception:  # pragma: no cover - optional selector should not break lane routing
    select_engineering_lane = None
try:
    from agent.redact import redact_sensitive_text
except Exception:  # pragma: no cover - defensive import for minimal tool contexts
    def redact_sensitive_text(text: str) -> str:
        return text

def _decisiondata_shared_home() -> Path:
    configured = os.getenv("DD_SHARED_HERMES_HOME")
    if configured:
        return Path(configured)
    canonical = Path("/Users/openclaw/.hermes")
    if canonical.exists():
        return canonical
    return Path.home() / ".hermes"


_HERMES_HOME = Path(os.getenv("HERMES_HOME") or (Path.home() / ".hermes"))
# The wrapper + lane config live under the SHARED ~/.hermes (openclaw-anchored),
# not a per-profile HERMES_HOME — mirror how the context tree resolves.
_SHARED_HOME = _decisiondata_shared_home()
_WRAPPER = _SHARED_HOME / "bin" / "dd-visible-lane-run"
_CHANNELS_JSON = _SHARED_HOME / "dd-lanes" / "channels.json"
_LANE_DIR = _SHARED_HOME / "dd-lanes"
# G2 (P5 review): the FULL 10-lane registry (a superset of channels.json). Only
# design/engineering/qa are Slack-backed (route_to_lane-able); the other 7 lanes
# (pmo, architecture, product, knowledge, devops, engineering-2/-3) run on the
# Telegram transport via this runner. The unknown-lane error reads this so it can
# tell P1 *"that lane is real — use the Telegram runner"* instead of a bare list
# of 3, which is exactly what let P1 silently drop the PMO step (session L22/L23).
_TELEGRAM_TARGETS_JSON = _SHARED_HOME / "dd-lanes" / "telegram-targets.json"
# Lane Registry Slice 1: the canonical roster projection (generated by
# bin/dd-lane-roster from the specialist_lanes Directus collection). When present,
# it is the source of truth for the lane list + capability routing; the JSON files
# above remain the fallback so behavior is unchanged if the projection is missing.
_ROSTER_PROJECTION = _SHARED_HOME / "dd-lanes" / "roster.generated.json"


def _roster_lanes() -> list[dict]:
    """The roster projection's lane records, or [] if absent/unreadable.

    READ-ONLY on a local generated file (no Directus call at tool time). Fail-soft:
    any error returns [] so the caller degrades to the legacy JSON sources.
    """
    try:
        proj = json.loads(_ROSTER_PROJECTION.read_text(encoding="utf-8"))
        return list(proj.get("lanes") or [])
    except Exception:
        return []


def resolve_capability(capability: str) -> Optional[str]:
    """Resolve a CAPABILITY to the best enabled lane_id via the roster projection.

    The capability-based routing primitive (Slice 1): callers can ask for a
    capability (e.g. ``security-review``) without knowing the physical lane, so a
    lane can be swapped/added without touching callers. Preference: route_to_lane-
    eligible lanes first, then deterministic lane_id order. Returns None if no
    enabled lane carries the capability (or the projection is absent).
    """
    cands = [
        l for l in _roster_lanes()
        if l.get("enabled") and capability in (l.get("capabilities") or [])
    ]
    if not cands:
        return None
    cands.sort(key=lambda l: (0 if l.get("route_to_lane_eligible") else 1, l.get("lane_id", "")))
    return cands[0].get("lane_id")
_TELEGRAM_RUNNER = _SHARED_HOME / "bin" / "dd-telegram-visible-lane-run"
# P-C / B-1a: the result-return SPINE. When a handoff returns PENDING (the lane
# detached and outlives the wrapper's watch budget), we register the run with the
# openclaw-owned reaper so it returns the closeout to THIS caller's session even
# after this turn ends. Without registration the finished run would orphan (G2).
_REAPER = _SHARED_HOME / "bin" / "dd-lane-reaper"

# Wrapper exit codes that mean "the lane never ran" (arg/config errors), vs a
# run that executed but the specialist returned a non-zero gate.
_WRAPPER_PREFLIGHT_CODES = {2, 3, 5, 6, 7, 8, 10}
# exit 75 (EX_TEMPFAIL) = the lane RAN but is still in flight (detached); the
# run survives and is collectable later via `dd-lane-run --poll <run_dir>`.
# This is an HONEST PENDING — neither success nor hard failure.
_WRAPPER_PENDING_CODE = 75
# exit 78 (EX_LEASE_HELD) = the work scope already has a LIVE mutation owner; the
# lane was REJECTED before it ran (single-owner lease). A clean rejection, not a
# run failure — distinct from the generic non-zero FAILED (Slice 1 / G1).
_WRAPPER_LEASE_HELD_CODE = 78


def _accepted_dispatch_on() -> bool:
    """Slice 1 / G1 — immediate-accept dispatch flag. Read per-call so it can be
    toggled via env without re-importing the tool. Default ON for the live burn-in
    (set DD_LANE_ACCEPTED_DISPATCH=0 to fall back to the prior error-shaped PENDING /
    generic FAILED without a revert). TRANSITIONAL — removed once the slice proves out."""
    return os.environ.get("DD_LANE_ACCEPTED_DISPATCH", "1") != "0"


def _build_accepted_envelope(lane: str, out: str, packet_path, reaper_note: str) -> str:
    """A NORMAL (non-error) accepted envelope for a detached run (G1).

    P1 receives ``state``/``run_id``/``lease`` immediately instead of blocking ~55s
    for an error-shaped PENDING. The reaper (already registered) delivers the real
    closeout as a later turn, so P1 must still NOT report this as completed. run_id
    is the run_dir basename; lease is the single-owner scope stamped at dispatch.
    """
    m = re.search(r"run_dir[=:]\s*(\S+)", out or "")
    run_dir = m.group(1).strip() if m else ""
    run_id = os.path.basename(run_dir) if run_dir else "(pending)"
    lease = ""
    if run_dir:
        try:
            with open(os.path.join(run_dir, "lease"), "r", encoding="utf-8", errors="replace") as fh:
                lease = fh.readline().strip()
        except OSError:
            lease = ""
    return (
        f"ACCEPTED — the '{lane}' lane was accepted and is running (detached).\n"
        f"state: accepted\n"
        f"run_id: {run_id}\n"
        f"lease: {lease or '(scope lease stamped on run)'}\n"
        f"The result-return reaper will deliver the lane's actual closeout "
        f"(branch/SHA/tests/status OR the exact blocker) back into THIS conversation "
        f"as a new turn when the run finishes, and mirror it to Telegram. Do NOT "
        f"report this as completed yet; wait for that closeout — you may continue "
        f"other work meanwhile.\n"
        f"packet: {packet_path}\n"
        f"{reaper_note}\n"
        f"{out or '(no status line)'}"
    )


# P-D / G5: gate verdicts on the wrapper's normalized status line that mean the
# specialist did NOT pass. The wrapper stamps the gate exit-code-first (a non-zero
# lane exit is an unconditional FAIL; a self-declared `Gate:` line may only refine
# a zero-exit). We treat any of these as "not OK" so a failed lane can never be
# reported as HANDOFF OK. PENDING is deliberately NOT here — it is the honest
# middle state handled by the dedicated PENDING branch (exit 75), not a failure.
_FAILURE_GATES = {"FAIL", "FAILED", "BLOCK", "BLOCKED", "ERROR", "STALLED", "NEEDS-YOU", "NEEDSYOU"}


def _parse_status_gate(out: str, lane: str) -> "str | None":
    """Extract the GATE token from the wrapper's normalized status line.

    The line is ``[<lane>] <GATE> | <oneline> | …``; we read the token between the
    ``[<lane>]`` prefix and the first ``|``. Returns the upper-cased gate, or None
    when no normalized line is present (caller treats that as "did not confirm").
    """
    if not out:
        return None
    prefix = f"[{lane}]"
    for line in out.splitlines():
        line = line.strip()
        if not line.startswith(prefix):
            continue
        rest = line[len(prefix):].strip()
        token = rest.split("|", 1)[0].strip()
        # The gate is the first whitespace-delimited word (e.g. "PASS", "FAIL").
        token = token.split()[0] if token.split() else ""
        return token.upper() or None
    return None


# ── Phase 3 (canary 72abe1ee 2026-06-17): exact-target verification contract ──
#
# When a caller (user → P1) names a URL/port/path as the acceptance surface, the
# lane closeout cannot say done/live unless THAT exact target is verified. The
# Slack/P1 canary on 2026-06-17 exposed two failure modes:
#   1. Deploy Ops claimed `8641` aligned, but the user had asked for `8641` while
#      the proof came from `8640` (canonical deploy target) — P1 wrongly accepted.
#   2. Even when Deploy Ops returned a proof artifact for `8641`, the user's
#      browser snapshot of `8641/settings` showed the regressed page — backend
#      proof contradicted by browser DOM. P1 wrongly accepted on first pass.
#
# Contract: if the goal/context mention specific http(s):// URLs (or a bare
# ``:port`` token), the lane result body must declare them VERIFIED — via lines
# like ``Verified: <url>``, ``verified_target: <url>``, ``Browser: <url> ok``. If
# none match, a clean PASS gate is downgraded to CHANGED-NOT-ACCEPTED ("blocked
# on exact-target verification") so P1 surfaces the gap instead of claiming done.
# A ``BROWSER-CONTRADICTS:`` (or ``Browser: ... DOES NOT MATCH``) line is the
# stronger "browser evidence wins" signal and is reported as a hard contradiction.

# Tokens callers use to declare an acceptance target inside the packet body. We
# accept several spellings so an existing packet template that already names a
# target ("Acceptance URL:", "Target:") still binds without rewording.
_REQUESTED_TARGET_PREFIXES = (
    "acceptance url",
    "acceptance target",
    "acceptance surface",
    "requested target",
    "requested acceptance",
    "review surface",
    "review url",
    "target url",
    "target",  # generic; matched last so the more specific tokens above win
)

# Tokens the lane result body uses to declare a target was actually verified.
# ``Verified:``/``verified_target:``/``Browser: <url> ok``/``Live:`` etc.
_VERIFIED_PREFIXES = (
    "verified target",
    "verified_target",
    "verified",
    "live",
    "browser",
)

# Strong "browser DOM contradicts deploy proof" markers — terminal block on the
# named target even if other proof rows look green.
_CONTRADICTION_MARKERS = (
    "browser-contradicts",
    "browser contradicts",
    "does not match",
    "still regressed",
    "still shows old",
    "browser-mismatch",
    "browser mismatch",
)

# A URL/port matcher tight enough to ignore prose. Captures:
#   * full http(s)://… URLs (path optional)
#   * bare host:port (with port 1024-65535 to avoid year/timestamp false-positives)
_URL_RE = re.compile(
    r"https?://[A-Za-z0-9.\-]+(?::\d{2,5})?(?:/[^\s<>`\"')]*)?",
    re.IGNORECASE,
)
_HOST_PORT_RE = re.compile(
    r"(?:^|[\s(,])(\d{1,3}(?:\.\d{1,3}){3}|[A-Za-z][A-Za-z0-9.\-]*):(\d{2,5})(?=/[^\s<>`\"')]*|[\s,)?]|$)",
)


def _normalize_target(token: str) -> str:
    """Normalize a target string for set comparison.

    Strips trailing punctuation, lowercases the host, drops a trailing slash from
    the path, drops default ports (http=80, https=443). Bare host:port becomes
    ``host:port`` (no scheme); URLs keep their scheme.
    """
    if not token:
        return ""
    t = token.strip().rstrip(".,;:)]>`'\"")
    # Pull off a trailing path-only slash but keep paths like /settings.
    if t.lower().startswith(("http://", "https://")):
        # split scheme://host[:port][/path]
        try:
            scheme, rest = t.split("://", 1)
        except ValueError:
            return t.lower()
        if "/" in rest:
            host_port, path = rest.split("/", 1)
            path = "/" + path
        else:
            host_port, path = rest, ""
        host_port = host_port.lower()
        # Drop default-port suffix so http://x:80/y == http://x/y.
        if scheme.lower() == "http" and host_port.endswith(":80"):
            host_port = host_port[: -len(":80")]
        elif scheme.lower() == "https" and host_port.endswith(":443"):
            host_port = host_port[: -len(":443")]
        if path == "/":
            path = ""
        return f"{scheme.lower()}://{host_port}{path}"
    # Bare host:port (or :port) — lowercase host.
    return t.lower()


def _extract_targets(text: str) -> list[str]:
    """Pull URL-shaped tokens from a free-text blob, deduped, in source order.

    Used to find user-named acceptance targets in the packet goal/context and to
    find lane-declared verified targets in the result body. Quoted/parenthesized
    forms are stripped; bare ``host:port`` segments are kept as-is so a request
    naming ``:8641`` still produces a target token.
    """
    if not text:
        return []
    seen: dict[str, None] = {}  # ordered set
    for m in _URL_RE.finditer(text):
        n = _normalize_target(m.group(0))
        if n:
            seen.setdefault(n, None)
    for m in _HOST_PORT_RE.finditer(text):
        token = f"{m.group(1)}:{m.group(2)}"
        n = _normalize_target(token)
        # Avoid double-counting tokens already produced by _URL_RE (those will be
        # ``http(s)://host:port…`` — strip the scheme to compare).
        if n in seen:
            continue
        # Don't capture a bare host:port if any URL with the same host:port path
        # is already present.
        if any(s.endswith(f"://{n}") or f"://{n}/" in s for s in seen):
            continue
        seen.setdefault(n, None)
    return list(seen.keys())


def _parse_requested_targets(packet_text: str) -> list[str]:
    """Find every URL/port/path the packet body explicitly names as an acceptance
    target.

    We look ONLY at lines that lead with an acceptance-token prefix (``Acceptance
    URL:``, ``Target:``, …). A URL casually mentioned elsewhere in the goal is NOT
    treated as a hard acceptance gate — only lines that read like a contract. This
    avoids over-blocking on prose like "see http://example.com for context".
    """
    if not packet_text:
        return []
    out: list[str] = []
    for raw_line in packet_text.splitlines():
        line = raw_line.strip().lstrip("-*•").strip()
        low = line.lower()
        if not any(
            low.startswith(p + ":") or low.startswith(p + " ") or low.startswith(p + "=")
            for p in _REQUESTED_TARGET_PREFIXES
        ):
            continue
        # Strip the prefix tag so we only extract from the value portion.
        # e.g. "Acceptance URL: http://x:8641/settings" → "http://x:8641/settings"
        body = line
        for p in _REQUESTED_TARGET_PREFIXES:
            if low.startswith(p + ":") or low.startswith(p + " ") or low.startswith(p + "="):
                body = line[len(p):].lstrip(":= \t")
                break
        for t in _extract_targets(body):
            if t not in out:
                out.append(t)
    return out


def _parse_verified_targets(result_text: str) -> list[str]:
    """Find every URL/port the lane result body declares VERIFIED.

    Matches lines that lead with a verification token (``Verified:``, ``Browser:``,
    …) AND positively assert success (the line contains a positive marker like
    ``ok``, ``pass``, ``matches``, ``accepted``, OR has NO negative marker).
    A line like ``Browser: http://x:8641/settings DOES NOT MATCH`` is NOT a
    verification — it's a contradiction (caught separately).
    """
    if not result_text:
        return []
    out: list[str] = []
    NEG = ("does not match", "regressed", "old ui", "fail", "fails", "blocked", "blocker", "mismatch")
    POS = ("ok", "pass", "matches", "accepted", "verified", "live", "confirmed", "200")
    for raw_line in result_text.splitlines():
        line = raw_line.strip().lstrip("-*•#").strip()
        low = line.lower()
        if not any(
            low.startswith(p + ":") or low.startswith(p + " ") or low.startswith(p + "=")
            for p in _VERIFIED_PREFIXES
        ):
            continue
        if any(neg in low for neg in NEG):
            continue
        if not any(pos in low for pos in POS):
            # No explicit positive marker — accept only if the line is JUST the
            # prefix + a URL (e.g. ``Verified: http://x:8641/settings``).
            stripped = low
            for p in _VERIFIED_PREFIXES:
                if stripped.startswith(p):
                    stripped = stripped[len(p):].lstrip(":= \t")
                    break
            # If only a URL/host:port remains, treat it as a positive verification.
            urls = _extract_targets(stripped)
            if not urls or urls[0] != stripped.split()[0].strip(".,;:)]>`'\"").lower() if stripped.split() else False:
                continue
        body = line
        for p in _VERIFIED_PREFIXES:
            if low.startswith(p + ":") or low.startswith(p + " ") or low.startswith(p + "="):
                body = line[len(p):].lstrip(":= \t")
                break
        for t in _extract_targets(body):
            if t not in out:
                out.append(t)
    return out


def _has_browser_contradiction(result_text: str) -> bool:
    """A loud "browser DOM contradicts the backend proof" marker in the result.

    When present, the lane's gate cannot stand even if every other proof row says
    PASS — the named target's actual surface still regressed.
    """
    if not result_text:
        return False
    low = result_text.lower()
    return any(m in low for m in _CONTRADICTION_MARKERS)


def _parse_targets_segment(out: str, lane: str) -> "dict | None":
    """Parse a ``| targets=verified=URL+URL;contradicts=0|1`` segment from the
    wrapper's single-line normalized status output (Phase 3).

    The wrapper extracts verified targets + browser-contradiction state from the
    lane's result body (which never crosses the wrapper boundary into stdout),
    then surfaces them as a compact segment on its normalized status line. Returns
    ``{"verified": [...], "contradicts": bool}`` when present, else None.
    """
    if not out:
        return None
    prefix = f"[{lane}]"
    for line in out.splitlines():
        line = line.strip()
        if not line.startswith(prefix):
            continue
        # Find the `targets=` token inside the pipe-delimited line.
        for seg in line.split("|"):
            seg = seg.strip()
            if not seg.lower().startswith("targets="):
                continue
            body = seg[len("targets="):]
            verified: list[str] = []
            contradicts = False
            for kv in body.split(";"):
                kv = kv.strip()
                if kv.lower().startswith("verified="):
                    raw = kv[len("verified="):]
                    # `+` is the inner separator (won't collide with URL chars
                    # the way `,` does).
                    for item in raw.split("+"):
                        item = item.strip()
                        if not item:
                            continue
                        n = _normalize_target(item)
                        if n and n not in verified:
                            verified.append(n)
                elif kv.lower().startswith("contradicts="):
                    val = kv[len("contradicts="):].strip().lower()
                    contradicts = val in ("1", "true", "yes")
            return {"verified": verified, "contradicts": contradicts}
        return None
    return None


def _target_match(requested: list[str], verified: list[str]) -> tuple[bool, list[str]]:
    """Is every requested target covered by at least one verified target?

    Returns (all_matched, missing). A requested target is covered when an entry in
    ``verified`` has the same normalized value OR (for a bare ``host:port``
    request) a verified URL contains that host:port.
    """
    if not requested:
        return True, []
    verified_set = set(verified)
    missing: list[str] = []
    for r in requested:
        if r in verified_set:
            continue
        # ``host:port`` request matched by any verified ``http(s)://host:port…``
        if not r.startswith(("http://", "https://")):
            host_port = r
            if any(
                v.startswith(("http://", "https://"))
                and (f"://{host_port}" in v or v.endswith(f"://{host_port}"))
                for v in verified
            ):
                continue
        missing.append(r)
    return (not missing), missing


def evaluate_exact_target_acceptance(
    packet_text: str, result_text: str
) -> dict:
    """Phase 3 verdict: did the lane verify the EXACT targets the caller named?

    Returns a dict with:
      * requested_acceptance_targets: list of URLs/ports named in the packet
      * verified_targets:             list of URLs/ports the result declared verified
      * target_match:                 True iff every requested is covered
      * browser_contradicts:          True iff the result body declares a browser
                                      DOM contradiction (terminal block)
      * status:                       "ok" (matched or no targets named),
                                      "not_accepted_on_target" (missing targets),
                                      "browser_contradiction" (terminal block)
      * missing:                      list of requested targets with no verify
    """
    requested = _parse_requested_targets(packet_text or "")
    verified = _parse_verified_targets(result_text or "")
    contradicts = _has_browser_contradiction(result_text or "")
    matched, missing = _target_match(requested, verified)
    if contradicts:
        status = "browser_contradiction"
    elif not requested:
        status = "ok"
    elif matched:
        status = "ok"
    else:
        status = "not_accepted_on_target"
    return {
        "requested_acceptance_targets": requested,
        "verified_targets": verified,
        "target_match": matched and not contradicts,
        "browser_contradicts": contradicts,
        "status": status,
        "missing": missing,
    }


def _parse_session_origin(session_key: str) -> "dict | None":
    """Parse a gateway session_key into platform/chat_type/chat_id/thread.

    Session keys follow ``agent:main:{platform}:{chat_type}:{chat_id}[:{extra}]``
    (mirrors gateway.run._parse_session_key). The 6th element is treated as a
    thread_id only for ``dm``/``thread`` chat types (where it is unambiguous);
    for group/channel it may be a per-user-isolation user_id, so we leave it out.
    Returns None when the key does not match.
    """
    if not session_key:
        return None
    parts = session_key.split(":")
    if len(parts) >= 5 and parts[0] == "agent" and parts[1] == "main":
        out = {"platform": parts[2], "chat_type": parts[3], "chat_id": parts[4]}
        if len(parts) > 5 and parts[3] in ("dm", "thread"):
            out["thread_id"] = parts[5]
        return out
    return None


def _originating_session_id(parent_agent) -> str:
    """The EXACT gateway session that dispatched this lane (WTS 17cbc96c).

    Preferred source is ``_dd_gateway_session_id``, which the gateway attaches
    per turn from its own session id — a trusted process fact, not a model
    argument. Older gateways do not set it; fall back to the last segment of the
    observability key (``agent:hermes:gateway:[<profile>:]<session>``), which is
    a sanitised form of the same id. Returns "" when neither is available, and a
    caller with "" writes NO authority record rather than a guessed one.
    """
    direct = str(getattr(parent_agent, "_dd_gateway_session_id", "") or "").strip()
    if direct:
        return direct
    obs = str(getattr(parent_agent, "_dd_session_key", "") or "").strip()
    if obs.startswith("agent:hermes:gateway:"):
        tail = obs.split(":")[-1].strip()
        if tail:
            return tail
    return ""


def _write_dispatch_authority(
    run_dir: str,
    parent_agent,
    origin: dict,
    *,
    lane: str = "",
    wts_task: Optional[str] = None,
    mission_id: Optional[str] = None,
) -> str:
    """Record WHO dispatched this run and WHERE its callback may return.

    Additive to the reaper's positional ``--register`` contract (which is left
    byte-identical): a versioned 0600 JSON sidecar in the run dir, read by the
    receiving gateway's admission check before a callback becomes a model turn.

    Returns a short non-secret status token for the caller-facing note.
    """
    try:
        from tools import dispatch_authority as da
    except Exception as exc:  # pragma: no cover - defensive
        return f"authority: UNWRITTEN ({type(exc).__name__})"

    session_id = _originating_session_id(parent_agent)
    caller = da.active_instance()
    if not caller or not session_id:
        # Never invent authority. A run dispatched without a nameable instance or
        # session gets NO record, so its callback is quarantined on return rather
        # than being admitted on a guess.
        missing = "instance" if not caller else "session"
        return f"authority: NOT RECORDED (no {missing}) — callback will be quarantined"

    record = da.build_authority(
        caller_instance=caller,
        destination_instance=caller,
        originating_session_id=session_id,
        run_id=Path(run_dir.rstrip("/")).name,
        run_dir=run_dir,
        lane=lane,
        wts_task=wts_task,
        mission_id=mission_id,
        platform=origin.get("platform", ""),
        chat_type=origin.get("chat_type", ""),
        chat_id=origin.get("chat_id", ""),
    )
    written = da.write_sidecar(run_dir, record)
    if not written:
        return "authority: UNWRITTEN (sidecar write failed) — callback will be quarantined"
    return f"authority: {da.SCHEMA} instance={caller} session={session_id}"


def _register_pending_with_reaper(
    out: str,
    parent_agent,
    wts_task: Optional[str] = None,
    *,
    lane: str = "",
    mission_id: Optional[str] = None,
) -> str:
    """P-C / B-1a: register a detached PENDING run with the openclaw reaper.

    The reaper (a standalone launchd agent) returns the lane's real closeout to
    THIS caller's session even after the turn ends — closing G1/G2/G3/G9. We give
    it the run_dir (surfaced on the wrapper's PENDING status line as
    ``run_dir=<path>``) plus the caller's session routing (parsed from
    ``parent_agent._dd_session_key``) so it knows where to deliver the result.

    We ALSO pass the resolved ``wts_task`` as the reaper's 8th --register arg so
    the reaper attaches the FINAL detached stdout result to that WTS task on reap
    (WTS 331b65f8 req 3/4). Without it the reaper registers wts_task=None and the
    final result attach is skipped — leaving only the synchronous-path PENDING
    placeholder on the task. The reaper's --register positional order is:
    ``run_dir session_key platform chat_id chat_type [thread_id] [budget] [wts_task]``
    so thread_id and budget MUST be present (even if empty/default) for wts_task
    to land in the right slot.

    Best-effort and fail-soft: a registration failure NEVER changes the PENDING
    result the caller sees (the run still survives and is pollable). Returns a
    short status token for the caller-facing message (booleans only; no secrets).
    """
    if not _REAPER.exists() or not os.access(_REAPER, os.X_OK):
        return "reaper-registration: skipped (reaper not installed)"
    m = re.search(r"run_dir[=:]\s*(\S+)", out or "")
    if not m:
        return "reaper-registration: skipped (no run_dir on status line)"
    run_dir = m.group(1).strip()
    # The reaper routes its result-return by platform+chat_id, which only the
    # *routing* session key (``agent:main:{platform}:{chat_type}:{chat_id}`` —
    # build_session_key output) carries. The gateway attaches that as
    # ``_dd_route_key``; ``_dd_session_key`` is the scrubbed MC-Live observability
    # grouping key (``agent:hermes:gateway:…``) and has no chat_id, so it never
    # parses here. Prefer the routing key; fall back to the observability key for
    # callers (tests / older gateways) that only set the latter.
    session_key = str(getattr(parent_agent, "_dd_route_key", "") or "").strip()
    origin = _parse_session_origin(session_key)
    if not origin:
        session_key = str(getattr(parent_agent, "_dd_session_key", "") or "").strip()
        origin = _parse_session_origin(session_key)
    if not origin:
        # We can still register the run for mirror-only return, but without a
        # caller session the re-inject (P1 reconciliation) cannot target a session.
        return "reaper-registration: skipped (no parseable caller session_key)"
    # Positional order matters: thread_id (slot 6) and budget (slot 7) MUST be
    # present so wts_task lands in slot 8. We pass an empty budget token ("") which
    # the reaper coerces to its DEFAULT_BUDGET_SECS — the empty string is a valid
    # "use default" sentinel, not a missing arg.
    wts = (wts_task or "").strip()
    # WTS 17cbc96c — write the authority sidecar BEFORE registering, so a run
    # that gets reaped immediately still has a record to be checked against.
    # Additive: the positional --register call below is unchanged.
    authority_note = _write_dispatch_authority(
        run_dir, parent_agent, origin, lane=lane, wts_task=wts_task, mission_id=mission_id,
    )
    cmd = [
        str(_REAPER), "--register", run_dir, session_key,
        origin["platform"], origin["chat_id"], origin["chat_type"],
        origin.get("thread_id", "") or "",
        "",          # budget → reaper default
        wts,         # wts_task → reaper attaches the final result MD to it on reap
    ]
    env = os.environ.copy()
    # route_to_lane always targets the shared DecisionData lane home, even when
    # the caller is a different Hermes home (for example Levi's .hermes-classic
    # Telegram assistant). Without forcing HERMES_HOME here, dd-lane-reaper
    # resolves its venv/registry under the caller's home and registration fails
    # with misleading PENDING/FAILED states for Telegram-only lanes.
    env["HERMES_HOME"] = str(_SHARED_HOME)
    env.setdefault("DD_HERMES_AGENT_DIR", str(_SHARED_HOME / "hermes-agent"))
    try:
        proc = subprocess.run(cmd, capture_output=True, text=True, timeout=30, env=env)
    except Exception as exc:
        return f"reaper-registration: FAILED to invoke ({type(exc).__name__})"
    if proc.returncode == 0:
        wts_note = f"; wts_task={wts}" if wts else "; wts_task=none (no final WTS attach)"
        return (f"reaper-registration: OK (run will return its closeout to this "
                f"session; run_dir={run_dir}{wts_note}; {authority_note})")
    return f"reaper-registration: FAILED (exit={proc.returncode}); {authority_note}"


def _known_lanes() -> list[str]:
    """The route_to_lane-ELIGIBLE lanes (Slack-backed).

    Slice 1: prefer the roster projection (route_to_lane_eligible + enabled lanes);
    fall back to channels.json so behavior is unchanged when the projection is
    absent. The roster reproduces design/engineering/qa as eligible, so existing
    routing is preserved.
    """
    roster = _roster_lanes()
    if roster:
        eligible = sorted(
            l["lane_id"] for l in roster
            if l.get("enabled") and l.get("route_to_lane_eligible") and l.get("lane_id")
        )
        if eligible:
            return eligible
    try:
        cfg = json.loads(_CHANNELS_JSON.read_text(encoding="utf-8"))
        return sorted((cfg.get("lanes") or {}).keys())
    except Exception:
        return []


def _all_lanes() -> list[str]:
    """The FULL specialist lane registry (Slack-backed + Telegram-only).

    Slice 1: prefer the roster projection (all enabled lanes); fall back to
    telegram-targets.json. Used to make the unknown-lane error actionable — so a
    real-but-not-Slack-backed lane (pmo/architecture/product/knowledge/devops/
    security/engineering-2/-3) is named and P1 is pointed at the Telegram runner
    instead of silently dropping the step. Returns [] on any read error.
    """
    roster = _roster_lanes()
    if roster:
        names = sorted(l["lane_id"] for l in roster if l.get("enabled") and l.get("lane_id"))
        if names:
            return names
    try:
        cfg = json.loads(_TELEGRAM_TARGETS_JSON.read_text(encoding="utf-8"))
        return sorted((cfg.get("lanes") or {}).keys())
    except Exception:
        return []


def check_route_to_lane_requirements() -> bool:
    """Gate: available only when the sanctioned wrapper + lane config exist.

    Returns a BOOLEAN — the registry's get_definitions() filters the tool out
    unless this returns True (a None/str return would be treated as falsy and
    silently drop the tool from the model's tool list).
    """
    if not _WRAPPER.exists() or not os.access(_WRAPPER, os.X_OK):
        return False
    if not _CHANNELS_JSON.exists():
        return False
    return True


def _write_packet(lane: str, goal: str, context: Optional[str], wts_task: Optional[str]) -> Path:
    """Materialize the handoff packet the wrapper sends to the lane.

    Includes a `WTS: <id>` line when an active task is supplied so the durable
    record is unambiguous even if the --wts-task flag path changes.
    """
    safe_lane = "".join(c for c in lane if c.isalnum() or c in "-_") or "lane"
    out_dir = _LANE_DIR / safe_lane
    out_dir.mkdir(parents=True, exist_ok=True)
    title = (goal or "").strip().splitlines()[0][:80] if goal else f"{lane} lane handoff"
    lines = [f"# DD P1 -> {lane} lane handoff: {title}", ""]
    if wts_task:
        lines.append(f"WTS: {wts_task}")
        lines.append("")
    lines.append("## Goal")
    lines.append((goal or "").strip())
    if context and context.strip():
        lines.append("")
        lines.append("## Context")
        lines.append(context.strip())
    # Deterministic-ish filename; timestamp is supplied by the caller turn, not here.
    fname = f"{safe_lane}-handoff.md"
    packet = out_dir / fname
    packet.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return packet


def route_to_lane(
    lane: str,
    goal: str,
    context: Optional[str] = None,
    wts_task: Optional[str] = None,
    packet: Optional[str] = None,
    preferred_lane: Optional[str] = None,
    affinity_reason: Optional[str] = None,
    mission_id: Optional[str] = None,
    purpose: Optional[str] = None,
    remediation_depth: Optional[int] = None,
    parent_agent=None,
) -> str:
    """Route a unit of work to a specialist lane via the sanctioned visible wrapper.

    Returns a concise, HONEST status string. Never reports success unless the
    lane actually ran and returned a result.
    """
    # Authority first — before argument parsing, packet writing, wrapper spawn or
    # reaper registration, so a refused caller creates no side effect (WTS 17cbc96c).
    denied = require_p1_caller("route_to_lane")
    if denied:
        return denied
    lane = (lane or "").strip()
    if not lane:
        return tool_error("route_to_lane: 'lane' is required (e.g. qa, design, engineering, engineering-pool).")
    if lane in {"engineering-pool", "engineering_pool", "engineering-auto"}:
        if select_engineering_lane is None:
            return tool_error("route_to_lane: engineering pool selector is not available; pick an explicit engineering lane.")
        selection = select_engineering_lane(preferred_lane=preferred_lane, affinity_reason=affinity_reason)
        if not selection.selected_lane:
            return tool_error(
                "HANDOFF BLOCKED — engineering pool has no safe capacity. "
                f"{selection.reason} Do NOT spawn duplicate recovery work; queue or ask P1/operator to decide."
            )
        assignment_reason = selection.reason
        lane = selection.selected_lane
        context_prefix = (
            "## Engineering Pool Assignment\n"
            f"Selected lane: {selection.selected_lane}\n"
            f"Selected agent: {selection.selected_agent}\n"
            f"Reason: {assignment_reason}\n"
            "Policy: Eng1 idle -> engineering; Eng1 busy -> engineering-2; "
            "Eng1+2 busy -> engineering-3; all busy -> no-capacity/queue. "
            "Same-active-engineer reuse requires explicit affinity reason.\n"
        )
        context = f"{context_prefix}\n{context or ''}".strip()
    known = _known_lanes()
    all_lanes = _all_lanes()
    telegram_only = [l for l in all_lanes if l not in known]
    wrapper = _WRAPPER
    transport = "Slack"
    if known and lane not in known:
        # P1-ORCH-1: real-but-Telegram-only lanes (pmo/product/architecture/devops/...)
        # are first-class route_to_lane targets now. The old behavior returned an
        # actionable shell command, but that still pushed P1 into hand-shelling; in
        # practice it hit permission/context issues and, worse, the finished run was
        # often reaped as an orphan with no caller session/wake metadata. Route them
        # through the sanctioned Telegram wrapper here so we can pass WTS and register
        # PENDING runs with the same reaper spine as Slack lanes.
        if lane in telegram_only:
            if not (_TELEGRAM_RUNNER.exists() and os.access(_TELEGRAM_RUNNER, os.X_OK)):
                return tool_error(
                    f"route_to_lane: lane '{lane}' is a REAL Telegram-only specialist "
                    f"lane, but the Telegram runner ({_TELEGRAM_RUNNER}) is not "
                    f"reachable/executable from this surface. Do NOT silently drop this "
                    f"step; surface the blocker to the user."
                )
            wrapper = _TELEGRAM_RUNNER
            transport = "Telegram"
        else:
            return tool_error(
                f"route_to_lane: unknown lane '{lane}' — it is not in ANY lane registry "
                f"(typo?). Do NOT silently drop this step; pick a real lane or tell the "
                f"user the requested lane does not exist.\n"
                f"route_to_lane-able lanes (Slack): {', '.join(known)}.\n"
                f"Telegram-only lanes: {', '.join(telegram_only) or '(none)'}.",
            )

    # WS8 §4 / P-D §G7
    # wts_task, DEFAULT it to the thread's bound id carried into the turn from the
    # Slack anchor (dd-slack-service stamps X-DD-WTS-Task-Id → the gateway exposes
    # it as parent_agent._dd_wts_task_id). This means every handoff+result carries
    # a durable tracker link by default — without P1 ever remembering the id.
    #   * An EXPLICIT wts_task arg always wins (the model may override).
    #   * No bound id present → empty → the wrapper fails honest (no bucket).
    # P-D / G7: the feed is now DEFAULT-ON (a missing anchor link is silent
    # corruption — "nothing should disappear"). Set ROUTE_TO_LANE_WTS_FEED=0
    # (or "false"/"off"/"no") for an EXPLICIT opt-out back to caller-supplied-only.
    _feed_flag = (os.getenv("ROUTE_TO_LANE_WTS_FEED") or "").strip().lower()
    _feed_on = _feed_flag not in ("0", "false", "off", "no")
    wts_source = "explicit" if (wts_task and wts_task.strip()) else "none"
    if (not (wts_task or "").strip()) and _feed_on:
        bound = getattr(parent_agent, "_dd_wts_task_id", None)
        if bound and str(bound).strip():
            wts_task = str(bound).strip()
            wts_source = "anchor-feed"

    # Resolve / build the packet.
    if packet:
        packet_path = Path(packet).expanduser()
        if not packet_path.is_file():
            return tool_error(f"route_to_lane: packet not found: {packet_path}")
    else:
        if not (goal or "").strip():
            return tool_error("route_to_lane: provide 'goal' (or an explicit 'packet' path).")
        packet_path = _write_packet(lane, goal, context, wts_task)

    # I1: build the CORRECT invocation — flags, never positional. Slack-backed
    # lanes use dd-visible-lane-run; Telegram-only lanes use
    # dd-telegram-visible-lane-run, but both preserve the same WTS + reaper spine.
    cmd = [str(wrapper), "--lane", lane, "--packet", str(packet_path)]
    if wts_task and wts_task.strip():
        cmd += ["--wts-task", wts_task.strip()]

    env = os.environ.copy()
    # The visible lane wrappers are shared DecisionData infrastructure. Pin their
    # home so a caller running from .hermes-classic (or any other HERMES_HOME)
    # cannot make the wrapper create run dirs / resolve reaper Python / write
    # registries under the wrong home.
    env["HERMES_HOME"] = str(_SHARED_HOME)
    env.setdefault("DD_HERMES_AGENT_DIR", str(_SHARED_HOME / "hermes-agent"))
    route_key = str(getattr(parent_agent, "_dd_route_key", "") or "").strip()
    session_key = str(getattr(parent_agent, "_dd_session_key", "") or "").strip()
    if route_key:
        env["HERMES_ROUTE_KEY"] = route_key
        env.setdefault("HERMES_SESSION_KEY", route_key)
    elif session_key:
        env.setdefault("HERMES_SESSION_KEY", session_key)
    if wts_task and wts_task.strip():
        env["DD_WTS_TASK_ID"] = wts_task.strip()
    # ── CALLER AUTHORITY for the spawn-time wake-target sidecar (WTS 17cbc96c) ──
    # HERMES_HOME is pinned to the SHARED home two lines above, so dd-lane-run
    # cannot derive who dispatched it — it would see the shared home and call
    # every caller "default". Pass the caller's real instance + exact session
    # explicitly. Both come from trusted process state (HERMES_HOME of THIS
    # process, and the gateway's own session id), never from a model argument.
    # Absent values are simply not set: dd-lane-run then writes a wake-target
    # with no authority, and the callback is quarantined on return.
    try:
        from tools import dispatch_authority as _da

        _caller_instance = _da.active_instance()
        _caller_session = _originating_session_id(parent_agent)
        if _caller_instance:
            env["DD_CALLER_INSTANCE"] = _caller_instance
        if _caller_session:
            env["DD_CALLER_SESSION_ID"] = _caller_session
    except Exception:
        pass
    # Slice C/D (DD_MISSION_ROOT): mission-bound dispatches carry the mission
    # through the wrapper into dd-lane-run (env fallback for --mission-id /
    # --purpose / --remediation-depth), where the pre-dispatch transition
    # validator enforces one-canonical-task / one-mutable-owner / read-only
    # recovery / bounded remediation. A rejected transition returns typed
    # MISSION_REJECTED (exit 76) with the reason — surface it, don't retry.
    # Lever 3 (Levi 2026-07-16): mission AUTO-BINDING. Canary #2 created the
    # mission root but never passed mission_id on dispatches, so the journal
    # (budgets, wall-clock, asks) stayed empty. Mirror the WTS anchor-feed:
    # when no explicit mission_id is given and a mission root exists whose
    # canonical task matches the bound WTS task, bind it automatically with a
    # lane-class default purpose. Explicit args always win; fail-soft.
    if (not mission_id or not str(mission_id).strip()) and wts_task and str(wts_task).strip():
        try:
            _mroot = _SHARED_HOME / "dd-lanes" / "missions"
            _best = None
            for _md in (_mroot.iterdir() if _mroot.is_dir() else []):
                try:
                    _r = json.loads((_md / "root.json").read_text(encoding="utf-8"))
                except Exception:
                    continue
                _mw = str(_r.get("wts_task") or "")
                if _mw and (_mw == str(wts_task).strip()
                            or _mw[:8] == str(wts_task).strip()[:8]):
                    if not _best or (_r.get("created_at") or "") > (_best[1].get("created_at") or ""):
                        _best = (_md.name, _r)
            if _best:
                mission_id = _best[0]
                if not purpose:
                    _lane_l = (lane or "").lower()
                    purpose = ("verify" if _lane_l == "qa"
                               else "deploy" if _lane_l in ("devops", "deploy-ops")
                               else "recover" if _lane_l == "knowledge"
                               else "implement")
        except Exception:
            pass
    if mission_id and str(mission_id).strip():
        env["DD_MISSION_ID"] = str(mission_id).strip()
        if purpose and str(purpose).strip():
            env["DD_MISSION_PURPOSE"] = str(purpose).strip()
        if remediation_depth is not None:
            env["DD_MISSION_DEPTH"] = str(int(remediation_depth))

    try:
        proc = subprocess.run(
            cmd, capture_output=True, text=True, timeout=900, env=env,
        )
    except subprocess.TimeoutExpired:
        return tool_error(
            f"route_to_lane: handoff to '{lane}' TIMED OUT (>900s). The lane did NOT "
            f"confirm completion — do NOT report this as done. Packet: {packet_path}"
        )
    except Exception as exc:
        return tool_error(f"route_to_lane: failed to invoke wrapper: {exc}")

    out = redact_sensitive_text((proc.stdout or "").strip())
    err = redact_sensitive_text((proc.stderr or "").strip())
    code = proc.returncode

    # I2 + P-D/G5: HONEST verification.
    # The wrapper prints exactly one normalized status line:
    #   [<lane>] <GATE> | <oneline> | #<channel> ts=<...> ...
    # HANDOFF OK requires ALL of:
    #   * exit==0 (the wrapper completed without a hard failure), AND
    #   * the normalized status line is present ([<lane>] prefix), AND
    #   * the parsed GATE is NOT a failure verdict.
    # G5: a specialist can exit 0 while its result body declares `Gate: FAIL`
    # (the wrapper now stamps the honest FAIL onto the status line, exit-code-first).
    # Accepting OK on exit==0 + prefix alone would hide that failure behind an
    # OK-shaped envelope. So we parse the gate and require it not be FAIL/BLOCK/etc.
    status_gate = _parse_status_gate(out, lane)
    gate_is_failure = status_gate in _FAILURE_GATES
    ran_ok = code == 0 and out.startswith(f"[{lane}]") and not gate_is_failure
    if (not ran_ok) and code == 0 and out.startswith(f"[{lane}]") and gate_is_failure:
        # The lane RAN and returned, but its gate is a FAILURE verdict. Report it
        # honestly as FAILED (with the gate + the wrapper's own status line), NOT
        # as a false OK. This is the G5 fix on the synchronous path.
        warn = ""
        if err:
            warn_lines = [l for l in err.splitlines() if "warn" in l.lower()]
            if warn_lines:
                warn = "\n[handoff warnings]\n" + "\n".join(warn_lines[:8])
        return tool_error(
            f"HANDOFF FAILED — the '{lane}' lane ran but returned a {status_gate} "
            f"gate (the specialist did NOT pass). Do NOT report this handoff as "
            f"succeeded; surface the failure and its detail to the user.\n"
            f"{out}"
            f"{warn}"
        )
    if ran_ok:
        # Phase 3 (canary 72abe1ee 2026-06-17): exact-target acceptance gate.
        # If the packet names specific http(s) URLs or ``:port``s as acceptance
        # targets and the lane result does NOT declare them verified, the OK
        # status is DOWNGRADED to "changed but not accepted on target" — exactly
        # the canary failure mode (8640 proof for an 8641 ask). A loud browser
        # contradiction is a stronger terminal block ("browser evidence wins").
        # The packet body is what carries the requested targets (packet_path is
        # the file the caller built above). The wrapper boundary hides the lane's
        # full result body from us, so the wrapper surfaces a compact
        # ``| targets=verified=A+B;contradicts=0|1`` segment on its single-line
        # normalized stdout, which we parse here. Falling back to scanning the
        # raw stdout itself catches an in-band result body too (legacy callers).
        packet_body = ""
        try:
            packet_body = Path(packet_path).read_text(encoding="utf-8", errors="replace")
        except Exception:
            packet_body = ""
        seg = _parse_targets_segment(out, lane)
        if seg is not None:
            # The wrapper did its own scan — synthesize a result blob so the
            # evaluator sees the same shape it would in the legacy path.
            synth = "\n".join(f"Verified: {u}" for u in seg["verified"]) + (
                "\nBrowser-contradicts: yes" if seg["contradicts"] else ""
            )
            verdict = evaluate_exact_target_acceptance(packet_body, synth)
        else:
            verdict = evaluate_exact_target_acceptance(packet_body, out)
        if verdict["status"] == "browser_contradiction":
            return tool_error(
                f"HANDOFF NOT-ACCEPTED — the '{lane}' lane returned a clean gate, "
                f"but the result body says the BROWSER DOM CONTRADICTS the backend "
                f"proof on the named acceptance target(s). Browser evidence wins "
                f"for user-facing UI acceptance — do NOT report this as done/live; "
                f"surface the contradiction to the user.\n"
                f"requested_acceptance_targets: {', '.join(verdict['requested_acceptance_targets']) or '(none parsed)'}\n"
                f"verified_targets: {', '.join(verdict['verified_targets']) or '(none)'}\n"
                f"{out}"
            )
        if verdict["status"] == "not_accepted_on_target":
            return tool_error(
                f"HANDOFF CHANGED-NOT-ACCEPTED — the '{lane}' lane returned a clean "
                f"gate, but the result body did NOT verify the EXACT acceptance "
                f"target(s) the caller named. Backend/canonical proof cannot "
                f"substitute for the named review surface. Do NOT report this as "
                f"done/live; report it as 'changed but blocked on exact-target "
                f"verification' and surface the missing targets.\n"
                f"requested_acceptance_targets: {', '.join(verdict['requested_acceptance_targets'])}\n"
                f"verified_targets: {', '.join(verdict['verified_targets']) or '(none declared)'}\n"
                f"missing: {', '.join(verdict['missing'])}\n"
                f"{out}"
            )
        # Surface any non-fatal delivery warnings (e.g. I3 bucket fallback) loudly.
        warn = ""
        if err:
            # keep only WARN/warn lines so P1 sees the bucket-fallback notice
            warn_lines = [l for l in err.splitlines() if "warn" in l.lower() or "WARN" in l]
            if warn_lines:
                warn = "\n[handoff warnings]\n" + "\n".join(warn_lines[:8])
        # When the packet DID name acceptance targets and they were all matched,
        # echo the match so the caller's closeout can quote them honestly.
        target_note = ""
        if verdict["requested_acceptance_targets"]:
            target_note = (
                "\n[exact-target verification]\n"
                f"requested: {', '.join(verdict['requested_acceptance_targets'])}\n"
                f"verified:  {', '.join(verdict['verified_targets'])}\n"
                f"target_match: true"
            )
        return (
            f"HANDOFF OK — routed to '{lane}' lane and the lane returned.\n"
            f"{out}"
            f"{target_note}"
            f"{warn}"
        )

    # PENDING — the lane RAN and is still in flight (detached); honest middle
    # state. NOT success (do not report done), NOT a hard failure.
    if code == _WRAPPER_PENDING_CODE:
        # P-C / B-1a: register the detached run with the reaper so its real
        # closeout returns to THIS session automatically (zero user follow-up).
        # Pass the resolved wts_task so the reaper attaches the FINAL result to the
        # bound task on reap (WTS 331b65f8 req 3/4) — not just the sync PENDING.
        reaper_note = _register_pending_with_reaper(
            out, parent_agent, wts_task, lane=lane, mission_id=mission_id,
        )
        # Slice 1 / G1: return a NORMAL accepted envelope (run_id + lease + state)
        # instead of an error-shaped PENDING. `pending` is not a failure.
        if _accepted_dispatch_on():
            return _build_accepted_envelope(lane, out, packet_path, reaper_note)
        return tool_error(
            f"HANDOFF PENDING — the '{lane}' lane started and is still running "
            f"(detached). You do NOT need to poll: the result-return reaper will "
            f"deliver the lane's actual closeout (branch/SHA/tests/status OR the "
            f"exact blocker) back into THIS conversation as a new turn when the run "
            f"finishes, and mirror it to Telegram. Do NOT report this as completed "
            f"yet; wait for that closeout.\n"
            f"packet: {packet_path}\n"
            f"{reaper_note}\n"
            f"{out or '(no status line)'}"
        )

    # LEASE_HELD — a clean single-owner rejection, distinct from a run failure
    # (Slice 1 / G1). Surface the owner pointer instead of an opaque generic FAILED.
    if _accepted_dispatch_on() and code == _WRAPPER_LEASE_HELD_CODE:
        held = ""
        for line in (out or "").splitlines():
            if line.strip().startswith("LEASE_HELD"):
                held = line.strip()
                break
        return tool_error(
            f"REJECTED (lease held) — the '{lane}' lane was NOT started: the work "
            f"scope already has a LIVE mutation owner (single-owner lease). This is "
            f"a clean rejection, NOT a run failure and NOT a completed handoff. Poll "
            f"or coordinate with the current owner, or request takeover once it is "
            f"terminal.\n"
            f"packet: {packet_path}\n"
            f"{held or out or '(no lease detail)'}"
        )

    # MISSION_REJECTED (Slice C/D) — the pre-dispatch transition validator refused
    # this dispatch BEFORE any run/lease existed (exit 76). Typed so P1 fixes the
    # transition instead of retrying into an opaque FAILED.
    if code == 76 or "MISSION_REJECTED" in (out or ""):
        return tool_error(
            f"MISSION_REJECTED — the '{lane}' dispatch is an INVALID mission "
            f"transition; nothing was dispatched (no run, no lease). Fix the "
            f"transition per the reason below (adopt recorded provenance / related "
            f"task + hold / wait for the active owner) — do NOT retry the same "
            f"dispatch.\n"
            f"packet: {packet_path}\n"
            f"{out or '(no detail)'}\n"
            f"{err[:800] or ''}"
        )

    # FAILED — be explicit; the lane did NOT complete a real run.
    if code in _WRAPPER_PREFLIGHT_CODES:
        reason = "the wrapper rejected the call before the lane ran (arg/config error)"
    elif code != 0:
        reason = "the lane ran but exited non-zero / did not return a clean result"
    else:
        reason = "the wrapper exited 0 but printed no normalized status line (lane did not confirm)"
    return tool_error(
        f"HANDOFF FAILED — did NOT reach a completed '{lane}' lane run; {reason} "
        f"(exit={code}). Do NOT report this handoff as succeeded.\n"
        f"packet: {packet_path}\n"
        f"stdout: {out or '(empty)'}\n"
        f"stderr: {err[:1500] or '(empty)'}"
    )


ROUTE_TO_LANE_SCHEMA = {
    "name": "route_to_lane",
    "description": (
        "Hand a unit of work to ANY DecisionData specialist LANE on EITHER transport "
        "and get its result back — the sanctioned, VISIBLE handoff for ALL lanes. "
        "Slack-backed: design, engineering (or 'engineering-pool'/-2/-3), qa. "
        "Telegram-backed (equally first-class here): pmo, architecture, product, "
        "knowledge, devops, deploy-ops, security. NEVER shell dd-visible-lane-run, "
        "dd-telegram-visible-lane-run, or dd-lane-run by hand — this tool picks the "
        "correct wrapper/transport, preserves the WTS + reaper result spine on both, "
        "and hand-shelled runs lose caller/wake metadata and orphan their results. "
        "It posts the visible handoff+result to the lane's channel, attaches BOTH the "
        "handoff (REQUEST) and result (RESPONSE) to the ACTIVE bound WTS task "
        "(precedence: wts_task arg > packet 'WTS:' line > the thread's anchor-bound id "
        "> none), and returns a TYPED honest status: ACCEPTED(run_id/lease, detached; "
        "closeout arrives as a later turn) · HANDOFF OK · HANDOFF FAILED(gate) · "
        "REJECTED(lease held) · MISSION_REJECTED(invalid mission transition). "
        "NEVER tell the user a handoff succeeded unless this tool returns HANDOFF OK, "
        "and never report ACCEPTED as completed."
    ),
    "parameters": {
        "type": "object",
        "properties": {
            "lane": {
                "type": "string",
                "description": "Specialist lane to route to — any registered lane on either transport: design, engineering, engineering-2, engineering-3, qa (Slack); pmo, architecture, product, knowledge, devops, deploy-ops, security (Telegram, equally first-class). Use 'engineering-pool' to select engineering/engineering-2/engineering-3 by active capacity before dispatch.",
            },
            "goal": {
                "type": "string",
                "description": "What the lane should accomplish — self-contained; the lane does not see your conversation. Becomes the handoff packet.",
            },
            "context": {
                "type": "string",
                "description": "Background the lane needs: paths, prior decisions, acceptance criteria, constraints.",
            },
            "wts_task": {
                "type": "string",
                "description": "The thread's ACTIVE bound WTS task id. Usually you can OMIT this on Slack-originated work — the thread's bound id is fed into the turn automatically and used as the default. Pass it explicitly only to override (e.g. a governance/Telegram handoff where you created the WTS task yourself). When neither is present the handoff is NOT attached to a durable record (no bucket).",
            },
            "packet": {
                "type": "string",
                "description": "Optional: path to a pre-written handoff packet .md. When given, goal/context are ignored and this file is sent verbatim.",
            },
            "preferred_lane": {
                "type": "string",
                "description": "Only with lane='engineering-pool': explicit engineering lane to reuse. If active, affinity_reason is required.",
            },
            "affinity_reason": {
                "type": "string",
                "description": "Only with lane='engineering-pool': dependency/file/surface/branch continuity reason allowing reuse of an active engineer.",
            },
            "mission_id": {
                "type": "string",
                "description": "Mission root id (dd-mission) this dispatch belongs to. When set, the dispatch is validated as a mission transition (one canonical WTS task, one mutable owner per scope, read-only recovery, bounded remediation) and journaled. Set it on every dispatch of a multi-lane mission.",
            },
            "purpose": {
                "type": "string",
                "enum": ["implement", "verify", "deploy", "recover", "remediate"],
                "description": "Only with mission_id: what this dispatch IS in the mission. 'recover' must be read-only (adopt recorded provenance — never rebuild); 'remediate' counts against the mission's max_remediation_depth.",
            },
            "remediation_depth": {
                "type": "integer",
                "description": "Only with mission_id + purpose='remediate': depth of this remediation (root work = 0, fixing a blocker in the root work = 1). Beyond the mission's max depth the dispatch is rejected — create a related task and hold.",
            },
        },
        "required": ["lane"],
    },
}


registry.register(
    name="route_to_lane",
    toolset="delegation",
    schema=ROUTE_TO_LANE_SCHEMA,
    handler=lambda args, **kw: route_to_lane(
        lane=args.get("lane"),
        goal=args.get("goal"),
        context=args.get("context"),
        wts_task=args.get("wts_task"),
        packet=args.get("packet"),
        parent_agent=kw.get("parent_agent"),
        preferred_lane=args.get("preferred_lane"),
        affinity_reason=args.get("affinity_reason"),
        mission_id=args.get("mission_id"),
        purpose=args.get("purpose"),
        remediation_depth=args.get("remediation_depth"),
    ),
    check_fn=check_route_to_lane_requirements,
    emoji="🛤️",
)
